let dashboardData = { agents: {}, logs: [], todos: [] };
let activityChart = null;
let modelChart = null;
let dashboardRefreshInterval = null;

async function loadDashboard(){if(!sbClient)return;const{data:logs}=await sbClient.from('agent_logs').select('*').order('created_at',{ascending:false}).limit(500);const{data:todos}=await sbClient.from('todos').select('*');dashboardData.logs=logs||[];dashboardData.todos=todos||[];renderAgentMonitor();renderSystemAnalytics();renderProjectRadar();}

function renderAgentMonitor(){const container=document.getElementById('agent-monitor');if(!container)return;container.innerHTML='';Object.entries(AGENTS).forEach(([key,agent])=>{const agentLogs=dashboardData.logs.filter(log=>log.agent_name.toLowerCase()===key);const latestLog=agentLogs[0];const lastActive=latestLog?new Date(latestLog.created_at):null;const isActive=lastActive&&(new Date()-lastActive)<10*60*1000;const model=latestLog?.model_used||'N/A';const task=latestLog?.task_description||'Agent Sleeping...';const card=document.createElement('div');card.className='glass-card p-4 flex flex-col gap-2';card.style.borderRadius='12px';card.style.background='rgba(255,255,255,0.05)';card.style.backdropFilter='blur(12px)';card.style.border='1px solid rgba(255,255,255,0.1)';card.style.boxShadow=`0 0 20px ${isActive?agent.color:'rgba(100,100,100,0.3)'}`;card.innerHTML=`<div class="flex items-center gap-2"><span class="text-xl">${agent.emoji}</span><span class="font-bold text-sm">${agent.name}</span><span class="w-2 h-2 rounded-full ml-auto" style="background: ${isActive?'#10B981':'#6B7280'}; ${isActive?'animation: pulse 2s infinite;':''}"></span></div><p class="text-xs text-gray-300 truncate">${task}</p><p class="text-xs text-gray-500">🧠 ${model}</p>`;container.appendChild(card);});}

function renderSystemAnalytics(){const now=new Date();const hours=[];for(let i=11;i>=0;i--){const h=new Date(now.getTime()-i*60*60*1000);hours.push({time:h.getHours()+':00',timestamp:h.getTime()});}const hourlyTasks=hours.map(h=>{const start=new Date(h.timestamp);const end=new Date(h.timestamp+60*60*1000);return dashboardData.logs.filter(log=>{const logTime=new Date(log.created_at).getTime();return logTime>=start&&logTime<end&&log.status==='completed'}).length;});if(activityChart){try{activityChart.destroy();}catch(e){}}const actCtx=document.getElementById('activity-chart');if(actCtx){const ctx=actCtx.getContext('2d');activityChart=new Chart(ctx,{type:'line',data:{labels:hours.map(h=>h.time),datasets:[{label:'Completed Tasks',data:hourlyTasks,borderColor:'#7C3AED',backgroundColor:'rgba(124, 58, 237, 0.1)',borderWidth:2,fill:true,tension:0.4}]},options:{responsive:true,maintainAspectRatio:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'rgba(255,255,255,0.05)'}},x:{grid:{color:'rgba(255,255,255,0.05)'}}}}});}const modelCounts={};dashboardData.logs.forEach(log=>{const model=log.model_used||'Unknown';modelCounts[model]=(modelCounts[model]||0)+1;});const models=Object.keys(modelCounts);const counts=Object.values(modelCounts);if(modelChart){try{modelChart.destroy();}catch(e){}}const modCtx=document.getElementById('model-chart');if(modCtx){const ctx=modCtx.getContext('2d');modelChart=new Chart(ctx,{type:'doughnut',data:{labels:models,datasets:[{data:counts,backgroundColor:['#7C3AED','#EC4899','#F59E0B','#10B981','#3B82F6']}]},options:{responsive:true,maintainAspectRatio:true,plugins:{legend:{position:'bottom'}}}});}const actLabel=document.getElementById('activity-label');if(actLabel)actLabel.textContent=`Activity Flow (${dashboardData.logs.filter(l=>l.status==='completed').length} completed)`;const modLabel=document.getElementById('model-label');if(modLabel)modLabel.textContent=`Model Distribution (${models.length} models)`;}

function renderProjectRadar(){const urgentTodos=dashboardData.todos.filter(t=>t.priority==='Urgent'&&t.status!=='done').slice(0,5);const urgentHtml=urgentTodos.map(t=>{const categoryColor={Work:'#7C3AED',Marketing:'#F59E0B',Development:'#10B981',Personal:'#06B6D4'};const color=categoryColor[t.category]||'#888';return `<div class="flex items-center gap-2 py-2 border-b border-white/10"><span class="px-2 py-1 rounded text-xs font-bold" style="background: rgba(${hexToRgb(color)}, 0.2); color: ${color};">${t.category}</span><span class="flex-1 text-sm text-gray-300">${t.title}</span><span class="text-xs text-gray-500">📅 ${t.due_date}</span></div>`;}).join('');const urgentQueue=document.getElementById('urgent-queue');if(urgentQueue)urgentQueue.innerHTML=urgentHtml||'<p class="text-gray-500 text-sm p-3">No urgent tasks</p>';const recentLogs=dashboardData.logs.slice(0,10);const feedHtml=recentLogs.map(log=>{const agent=Object.values(AGENTS).find(a=>a.name.toLowerCase()===log.agent_name.toLowerCase());const time=new Date(log.created_at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});const status=log.status==='completed'?'✅':'❌';return `<div class="text-xs font-mono text-gray-300 py-1">[${time}] ${agent?.emoji||'⚙️'} ${agent?.name||log.agent_name} → ${log.task_description.substring(0,40)}... ${status}</div>`;}).join('');const recentFeed=document.getElementById('recent-feed');if(recentFeed)recentFeed.innerHTML=feedHtml;}

function hexToRgb(hex){const result=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);return result?`${parseInt(result[1],16)}, ${parseInt(result[2],16)}, ${parseInt(result[3],16)}`:'100, 100, 100';}

function startDashboardRefresh(){if(dashboardRefreshInterval)clearInterval(dashboardRefreshInterval);loadDashboard();dashboardRefreshInterval=setInterval(loadDashboard,30000);}

function stopDashboardRefresh(){if(dashboardRefreshInterval){clearInterval(dashboardRefreshInterval);dashboardRefreshInterval=null;}}
