const SUPABASE_URL = 'https://svdibokdzetmzivfvepf.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZGlib2tkemV0bXppdmZ2ZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0ODk0MDIsImV4cCI6MjA4OTA2NTQwMn0.seParGlECiuaV1CoJkQv3_V25z4E4rsS-jiTkVNrTjs';
let sbClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let kanbanTasks = [];
let productivityChart = null;
let draggedTask = null;
async function loadTasksTab(){if(!sbClient)return;const{data:tasks,error}=await sbClient.from('todos').select('*').order('created_at',{ascending:false});if(error){console.error('Error:',error);return;}kanbanTasks=tasks||[];renderKanbanBoard();updateProductivityStats();}
function renderKanbanBoard(){const categoryFilter=document.getElementById('filter-category')?document.getElementById('filter-category').value:'';const priorityFilter=document.getElementById('filter-priority')?document.getElementById('filter-priority').value:'';let filtered=kanbanTasks;if(categoryFilter)filtered=filtered.filter(t=>t.category===categoryFilter);if(priorityFilter)filtered=filtered.filter(t=>t.priority===priorityFilter);const columns={todo:[],in_progress:[],done:[]};filtered.forEach(task=>{const status=task.status||'todo';if(columns[status])columns[status].push(task);});if(document.getElementById('column-todo'))document.getElementById('column-todo').innerHTML=columns.todo.map(t=>renderTaskCard(t)).join('');if(document.getElementById('column-doing'))document.getElementById('column-doing').innerHTML=columns.in_progress.map(t=>renderTaskCard(t)).join('');if(document.getElementById('column-done'))document.getElementById('column-done').innerHTML=columns.done.map(t=>renderTaskCard(t)).join('');if(document.getElementById('count-todo'))document.getElementById('count-todo').textContent=columns.todo.length;if(document.getElementById('count-doing'))document.getElementById('count-doing').textContent=columns.in_progress.length;if(document.getElementById('count-done'))document.getElementById('count-done').textContent=columns.done.length;attachDragListeners();}
function renderTaskCard(task){const categoryColor={Work:'#7C3AED',Marketing:'#F59E0B',Development:'#10B981',Personal:'#06B6D4'};const priorityColor={Urgent:'#EF4444',Normal:'#3B82F6',Someday:'#6B7280'};const trackColor={'On Track':'#10B981','At Risk':'#F59E0B','Off Track':'#EF4444'};return `<div class="task-card glass-card p-4 rounded-lg cursor-grab active:cursor-grabbing" draggable="true" data-task-id="${task.id}"><div class="flex items-start gap-3 mb-3"><input type="checkbox" ${task.completed?'checked':''} onchange="toggleComplete('${task.id}', this.checked)" class="mt-1"><div class="flex-1"><p class="font-bold text-white">${task.title}</p></div><div class="text-lg cursor-pointer" onclick="openMenu(event, '${task.id}')">⋮</div></div><div class="flex flex-wrap gap-2 mb-3"><span class="px-2 py-1 rounded text-xs font-bold" style="background: rgba(${hexToRgb(categoryColor[task.category])}, 0.2); color: ${categoryColor[task.category]};">${task.category}</span><span class="px-2 py-1 rounded text-xs font-bold" style="background: rgba(${hexToRgb(priorityColor[task.priority])}, 0.2); color: ${priorityColor[task.priority]};">${task.priority}</span><span class="px-2 py-1 rounded text-xs font-bold" style="background: rgba(${hexToRgb(trackColor[task.track_status])}, 0.2); color: ${trackColor[task.track_status]};">${task.track_status}</span></div><p class="text-xs text-gray-400">📅 ${task.due_date}</p></div>`;}
function attachDragListeners(){document.querySelectorAll('.task-card').forEach(card=>{card.addEventListener('dragstart',(e)=>{draggedTask=e.target.closest('.task-card');e.dataTransfer.effectAllowed='move';});card.addEventListener('dragend',()=>{draggedTask=null;});});['column-todo','column-doing','column-done'].forEach(colId=>{const col=document.getElementById(colId);if(!col)return;col.addEventListener('dragover',(e)=>{e.preventDefault();e.dataTransfer.dropEffect='move';col.style.opacity='0.7';});col.addEventListener('dragleave',()=>{col.style.opacity='1';});col.addEventListener('drop',async(e)=>{e.preventDefault();col.style.opacity='1';if(draggedTask){const taskId=draggedTask.getAttribute('data-task-id');const newStatus=colId==='column-todo'?'todo':colId==='column-doing'?'in_progress':'done';await updateTaskStatus(taskId,newStatus);}});});}
async function updateTaskStatus(taskId,newStatus){if(!sbClient)return;const{error}=await sbClient.from('todos').update({status:newStatus}).eq('id',taskId);if(error)console.error('Error:',error);else{kanbanTasks=kanbanTasks.map(t=>t.id===taskId?{...t,status:newStatus}:t);renderKanbanBoard();updateProductivityStats();}}
async function toggleComplete(taskId,completed){if(!sbClient)return;const{error}=await sbClient.from('todos').update({completed}).eq('id',taskId);if(error)console.error('Error:',error);else{kanbanTasks=kanbanTasks.map(t=>t.id===taskId?{...t,completed}:t);renderKanbanBoard();updateProductivityStats();}}
function editTask(taskId){const task=kanbanTasks.find(t=>t.id===taskId);if(!task)return;document.getElementById('edit-task-id').value=taskId;document.getElementById('edit-title').value=task.title;document.getElementById('edit-category').value=task.category;document.getElementById('edit-priority').value=task.priority;document.getElementById('edit-track-status').value=task.track_status;document.getElementById('edit-due-date').value=task.due_date;document.getElementById('edit-modal').classList.remove('hidden');}
function closeEditModal(){document.getElementById('edit-modal').classList.add('hidden');}
async function saveTask(e){e.preventDefault();const taskId=document.getElementById('edit-task-id').value;const updates={title:document.getElementById('edit-title').value,category:document.getElementById('edit-category').value,priority:document.getElementById('edit-priority').value,track_status:document.getElementById('edit-track-status').value,due_date:document.getElementById('edit-due-date').value};if(!sbClient)return;const{error}=await sbClient.from('todos').update(updates).eq('id',taskId);if(error)console.error('Error:',error);else{kanbanTasks=kanbanTasks.map(t=>t.id===taskId?{...t,...updates}:t);closeEditModal();renderKanbanBoard();}}
async function deleteTask(taskId){if(!confirm('Delete this task?'))return;if(!sbClient)return;const{error}=await sbClient.from('todos').delete().eq('id',taskId);if(error)console.error('Error:',error);else{kanbanTasks=kanbanTasks.filter(t=>t.id!==taskId);renderKanbanBoard();updateProductivityStats();}}
function hexToRgb(hex){const result=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);return result?`${parseInt(result[1],16)}, ${parseInt(result[2],16)}, ${parseInt(result[3],16)}`:'100, 100, 100';}
function updateProductivityStats(){const total=kanbanTasks.length;const todoCount=kanbanTasks.filter(t=>t.status==='todo').length;const doingCount=kanbanTasks.filter(t=>t.status==='in_progress').length;const doneCount=kanbanTasks.filter(t=>t.status==='done').length;const todoPct=total>0?Math.round((todoCount/total)*100):0;const doingPct=total>0?Math.round((doingCount/total)*100):0;const donePct=total>0?Math.round((doneCount/total)*100):0;if(document.getElementById('stat-todo'))document.getElementById('stat-todo').textContent=todoCount;if(document.getElementById('stat-todo-total'))document.getElementById('stat-todo-total').textContent=total;if(document.getElementById('stat-todo-pct'))document.getElementById('stat-todo-pct').textContent=todoPct;if(document.getElementById('stat-doing'))document.getElementById('stat-doing').textContent=doingCount;if(document.getElementById('stat-doing-total'))document.getElementById('stat-doing-total').textContent=total;if(document.getElementById('stat-doing-pct'))document.getElementById('stat-doing-pct').textContent=doingPct;if(document.getElementById('stat-done'))document.getElementById('stat-done').textContent=doneCount;if(document.getElementById('stat-done-total'))document.getElementById('stat-done-total').textContent=total;if(document.getElementById('stat-done-pct'))document.getElementById('stat-done-pct').textContent=donePct;const motivation=donePct<=30?"Just getting started — let's go! 🚀":donePct<=60?"Good progress — keep pushing! 💪":donePct<=90?"Almost there — finish strong! 🔥":"Outstanding — you crushed it! 🏆";if(document.getElementById('motivational-badge'))document.getElementById('motivational-badge').textContent=motivation;if(productivityChart)productivityChart.destroy();const ctx=document.getElementById('productivity-chart');if(ctx){productivityChart=new Chart(ctx,{type:'doughnut',data:{labels:['To Do','Doing','Done'],datasets:[{data:[todoCount,doingCount,doneCount],backgroundColor:['#3B82F6','#F59E0B','#10B981']}]},options:{responsive:true,maintainAspectRatio:true,plugins:{legend:{display:false}}}});}}
document.addEventListener('DOMContentLoaded',()=>{const tabButtons=document.querySelectorAll('.nav-tab');const tabContents=document.querySelectorAll('.tab-content');tabButtons.forEach(button=>{button.addEventListener('click',()=>{const tabName=button.getAttribute('data-tab');tabButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');tabContents.forEach(content=>{content.classList.add('hidden');content.classList.remove('fade-in');});const activeTab=document.getElementById(`${tabName}-tab`);activeTab.classList.remove('hidden');activeTab.classList.add('fade-in');if(tabName==='tasks'&&sbClient)loadTasksTab();});});document.getElementById('filter-category')?.addEventListener('change',renderKanbanBoard);document.getElementById('filter-priority')?.addEventListener('change',renderKanbanBoard);});
